support regex

diff --git a/wlxt b/wlxt
--- a/wlxt
+++ b/wlxt
@@ -25,9 +25,12 @@ function getCookie(){
         echo -e "Please specify your identity.\n\nwlxt config id <your_student_id>\nwlxt config password <your_password>\nwlxt config semester <semester_id> (e.g. 2024-2025-2)\n"
         exit 1
     fi
+    
+    ping -w 1 -c 1 101.6.15.67 > /dev/null 2> /dev/null
+    if [ $? != 0 ]; then echo "Cannot connect to learn.tsinghua.edu.cn. Please check your internet connection."; exit 1; fi
 
     if [ ! -f "$Cookie" ] || [ $(date +%s) -gt $(awk '$6=="XSRF-TOKEN"{print $5-120}' "$Cookie" ) ]; then
-        mkdir -p $(dirname "$Cookie")
+        # mkdir -p $(dirname "$Cookie")
         echo "Please wait for a second..."
         curl -s "https://id.tsinghua.edu.cn/do/off/ui/auth/login/post/bb5df85216504820be7bba2b0ae1535b/0?/login.do" -d i_user=$username -d i_pass=$password | sed -nE 's/^.*href="(.*)".*$/\1/p' | xargs curl -s | sed -nE 's/^.*window\.location="(.*)".*$/https:\/\/learn.tsinghua.edu.cn\1/p' | xargs curl -s -L -c "$Cookie" > /dev/null 2> /dev/null
         if [ $? -ne 0 ]; then
@@ -55,7 +58,6 @@ function getCourse(){
 
     function findCourse(){
         clist=()
-        if [ "$1" == "-" ]; then clist=("${idlist[@]}"); return; fi
         for id in "${idlist[@]}"
         do
             if [ "$1" == $id ]; then clist[0]=$id; fi
@@ -67,7 +69,7 @@ function getCourse(){
             kcm=$(echo "$Courses" | jq -r '.["'$id'"]["kcm"]')
             ywkcm=$(echo "$Courses" | jq -r '.["'$id'"]["ywkcm"]')
             surname=$(cat "$Config" | jq -r '.["surnames"]["'$id'"] // empty')
-            if [ "$1" == "$kcm" ] || [ "$1" == "$ywkcm" ] || [ "$1" == "$surname" ]; then
+            if [ "$1" == "$kcm" ] || [ "$1" == "$ywkcm" ] || [ "$(echo "$surname" | grep -E "$1")" ]; then
                 clist[$i]=$id
                 i=$((i+1))
             fi
@@ -412,8 +414,8 @@ elif [ "$1" == "wj" ]; then
         for flid in "${flidlist[@]}"; do printfiles $id $flid; done
     done
 elif [ "$1" == "xzwj" ]; then
-    if [ $# -lt 3 ] || [ $# -gt 4 ] || ([ "$4" ] && [ "$4" != "-a" ]); then 
-        echo "Usage: wlxt xzwj <course_name> <base_directory> [-a]"
+    if [ $# -lt 3 ] || [ $# -gt 4 ]; then 
+        echo "Usage: wlxt xzwj <course_name> <base_directory> [title]"
         exit 1
     fi
     getFiles
@@ -447,8 +449,8 @@ elif [ "$1" == "xzwj" ]; then
             findFiles $id $flid
             for f in "${flist[@]}"
             do
-                IFS=$'\t' read wjid stat <<< $(echo "$f" | jq -r '.["wjid"], .["stat"]' | tr '\n' '\t')
-                if [ "$stat" == "1" ] || [ "$4" ]; then downloadfile $wjid "$bdir/$kcm/$flm"; fi
+                IFS=$'\t' read wjid stat bt <<< $(echo "$f" | jq -r '.["wjid"], .["stat"], .["bt"]' | tr '\n' '\t')
+                if ([ ! "$4" ] && [ "$stat" == "1" ]) || [ "$(echo "$bt" | grep -E "$4")" ]; then downloadfile $wjid "$bdir/$kcm/$flm"; fi
             done
         done
     done
